%YAML:1.0
# 路径
datasetDir: dataset/rgbd_dataset_freiburg3_long_office_household/rgb
startIndex: 0

# 相机内参
Camera.fx: 535.4
Camera.fy: 539.2
Camera.cx: 320.1
Camera.cy: 247.6

# BA
#// Scaling
#// -------
#// Given one robustifier
#//   s -> rho(s)
#// one can change the length scale at which robustification takes
#// place, by adding a scale factor 'a' as follows:
#//
#//   s -> a^2 rho(s / a^2).
#//
#// The first and second derivatives are:
#//
#//   s -> rho'(s / a^2),
#//   s -> (1 / a^2) rho''(s / a^2),
#//
#// but the behaviour near s = 0 is the same as the original function,
#// i.e.
#//
#//   rho(s) = s + higher order terms,
#//   a^2 rho(s / a^2) = s + higher order terms.
#//
#// The scalar 'a' should be positive.
#//
#// The reason for the appearance of squaring is that 'a' is in the
#// units of the residual vector norm whereas 's' is a squared
#// norm. For applications it is more convenient to specify 'a' than
#// its square. The commonly used robustifiers below are described in
#// un-scaled format (a = 1) but their implementations work for any
#// non-zero value of 'a'.
#
#// Huber.
#//
#//   rho(s) = s               for s <= 1,
#//   rho(s) = 2 sqrt(s) - 1   for s >= 1.
#//
#// At s = 0: rho = [0, 1, 0].
#//
#// The scaling parameter 'a' corresponds to 'delta' on this page:
#//   http://en.wikipedia.org/wiki/Huber_Loss_Function
BA.lossFunction.scaling: 2

# 描述子提取的数量
VO.nfeatures: 200

# 特征点算法

VO.featureType: ORB
#    @param scaleFactor Pyramid decimation ratio, greater than 1. scaleFactor==2 means the classical
#    pyramid, where each next level has 4x less pixels than the previous, but such a big scale factor
#    will degrade feature matching scores dramatically. On the other hand, too close to 1 scale factor
#    will mean that to cover certain scale range you will need more pyramid levels and so the speed
#    will suffer.
VO.ORB.scaleFactor: 1.2
#    @param nlevels The number of pyramid levels. The smallest level will have linear size equal to
#    input_image_linear_size/pow(scaleFactor, nlevels - firstLevel).
VO.ORB.nlevels: 8
#    @param fastThreshold
VO.ORB.fastThreshold: 5


# MapViewer的背景颜色
MapViewer.backgroundColor.r: 0.8
MapViewer.backgroundColor.g: 0.8
MapViewer.backgroundColor.b: 0.8
# MapViewer进行update后是否等待按键
MapViewer.updateWait: 0
# 镜头与当前帧的距离
MapViewer.disCamera: 100
# 是否自动跟踪当前帧
MapViewer.trackCurrFrame: 1
# 是否画norm
MapViewer.drawNorms: 0


# 特征匹配方式
Matcher.matcherType: BruteForce-Hamming

# 用于解对极约束的最少点数
Solver2D2D.minInlierNum: 50
# 用于解对极约束的最小内点比例
Solver2D2D.minInlierRatio: 0.3
# 首先筛选前rankRatio比例的匹配
Solver2D2D.Matcher.rankRatio: 0.5
# 特征距离阈值相对最小特征距离的比例
Solver2D2D.Matcher.disThresRatio: 5
# 特征阈值的最小值，防止阈值过小选出的点不够
# Matcher.disThresMin: 30
Solver2D2D.Matcher.disThresMin: 150
# 如果testRatio不为0，通过knnMatch获得距离最近的两个match
# 测试第一个match的距离是否小于第二个match的距离的testRatio倍
# 0 <= testRati < 1
Solver2D2D.Matcher.testRatio: 0.8

# 用于解PnP选取的最多局部地图点 TODO:（暂时取消）
Solver3D2D.max3Dnum: 500
# 用于解PnP选取的最少局部地图点
Solver3D2D.min3Dnum: 30
# 用于解PnP选取的局部地图点距离范围
Solver3D2D.max3Ddis: 50
# 用于解PnP的最少点数
Solver3D2D.minInlierNum: 10
# 用于解PnP的最小内点比例
Solver3D2D.minInlierRatio: 0.3
# 首先筛选前rankRatio比例的匹配
Solver3D2D.Matcher.rankRatio: 0.8
# 特征距离阈值相对最小特征距离的比例
Solver3D2D.Matcher.disThresRatio: 10
# 特征阈值的最小值，防止阈值过小选出的点不够
# Matcher.disThresMin: 30
Solver3D2D.Matcher.disThresMin: 300
# 如果testRatio不为0，通过knnMatch获得距离最近的两个match
# 测试第一个match的距离是否小于第二个match的距离的testRatio倍
# 0 <= testRati < 1
Solver3D2D.Matcher.testRatio: 0.8

# 三角化点到两帧的最大距离相对于帧间距的最大比例
Triangulater.maxDisRatio: 200
Triangulater.minDisRatio: 1
# 重投影误差最大值 TODO:（暂时取消）
Triangulater.maxReprojErr: 30

# local_map
# 最少关键点数
# 如果当前局部地图关键帧数等于最大关键帧数，且关键点数小于最少关键点数，则增加最大关键帧数
# 否则减小最大关键帧数
LocalMap.minMapPoints: 500
# 地图点到每个观测帧的最大距离
LocalMap.maxInlierPointDis: 150
# 关键帧最大数量，超过此数量删除旧关键帧
LocalMap.minKeyFrames: 8
# 重投影误差最大值
LocalMap.maxReprojErr: 50
# 首先筛选前rankRatio比例的匹配
LocalMap.Matcher.rankRatio: 0.5
# 特征距离阈值相对最小特征距离的比例
LocalMap.Matcher.disThresRatio: 3
# 特征阈值的最小值，防止阈值过小选出的点不够
# Matcher.disThresMin: 30
LocalMap.Matcher.disThresMin: 100
# 如果testRatio不为0，通过knnMatch获得距离最近的两个match
# 测试第一个match的距离是否小于第二个match的距离的testRatio倍
# 0 <= testRati < 1
LocalMap.Matcher.testRatio: 0.8

# tracking

# 初始化两帧的最大间隔帧数
Initializer.maxFrameInterval: 40
# 初始化两帧的最小间隔帧数
Initializer.minFrameInterval: 10
# 初始化地图的最小点数
Initializer.minMapPointNum: 50

# 关键帧的最小间距
Tracker.minKeyFrameDis: 0.5
# 关键帧的最大间距
Tracker.maxKeyFrameDis: 10
# 关键帧的最少地图点
Tracker.minKeyFrameInlierNum: 20
# 关键帧之间的最小间隔帧数
Tracker.minKeyFrameInterval: 2
# 关键帧解PnP所用地图点数相对于上一关键帧的最大比例
Tracker.maxKeyFrameTrackRatio: 0.8


