%YAML:1.0
# 路径
datasetDir: dataset/rgbd_dataset_freiburg2_large_with_loop/rgb

# 相机内参
Camera.fx: 520.9
Camera.fy: 521.0
Camera.cx: 325.1
Camera.cy: 249.7

# 描述子提取的数量
VO.nfeatures: 1000
# 特征点算法
VO.featureType: SIFT
# VO.featureType: ORB

# MapViewer的背景颜色
MapViewer.backgroundColor.r: 0.8
MapViewer.backgroundColor.g: 0.8
MapViewer.backgroundColor.b: 0.8
# MapViewer进行update后是否等待按键
MapViewer.updateWait: 1

# 特征距离阈值相对最小特征距离的比例
Matcher.disThresRatio: 5
# 特征阈值的最小值，防止阈值过小选出的点不够
# Matcher.disThresMin: 30
Matcher.disThresMin: 100
# 如果testRatio不为0，通过knnMatch获得距离最近的两个match
# 测试第一个match的距离是否小于第二个match的距离的testRatio倍
# 0 <= testRati < 1
Matcher.testRatio: 0.8
# 特征匹配方式
Matcher.matcherType: BruteForce
# Matcher.matcherType: BruteForce-Hamming

# 用于解对极约束的最少点数
Solver2D2D.minInlierNum: 100
# 用于解对极约束的最小内点比例
Solver2D2D.minInlierRatio: 0.3

# 用于解PnP选取的最多局部地图点（暂时取消）
Solver3D2D.max3Dnum: 500
# 用于解PnP选取的最少局部地图点
Solver3D2D.min3Dnum: 10
# 用于解PnP选取的局部地图点距离范围
Solver3D2D.max3Ddis: 50
# 用于解PnP的最少点数
Solver3D2D.minInlierNum: 8
# 用于解PnP的最小内点比例
Solver3D2D.minInlierRatio: 0.3

# 三角化点到两帧的最大距离相对于帧间距的最大比例
Triangulater.maxDisRatio: 50
Triangulater.minDisRatio: 1
# 重投影误差最大值
Triangulater.maxReprojErr: 50

# local_map
# 地图点到每个观测帧的最大距离
LocalMap.maxInlierPointDis: 50
# 关键帧最大数量，超过此数量删除旧关键帧
LocalMap.maxKeyFrames: 7

# tracking

# 初始化两帧的最大间隔帧数
Initializer.maxFrameInterval: 40
# 初始化两帧的最小间隔帧数
Initializer.minFrameInterval: 10
# 初始化地图的最小点数
Initializer.minMapPointNum: 100

# 关键帧的最小间距
Tracker.minKeyFrameDis: 1
# 关键帧的最大间距
Tracker.maxKeyFrameDis: 3
# 关键帧的最少地图点
Tracker.minKeyFrameInlierNum: 30
# 关键帧之间的最小间隔帧数
Tracker.minKeyFrameInterval: 10
# 关键帧解PnP所用地图点数相对于上一关键帧的最大比例
Tracker.maxKeyFrameTrackRatio: 1
